windows:
  dotfiles: ~/.dotfiles
  link_type: 'Symbolic'
  shell_command: powershell -noprofile -nologo -c {{ quote "" cmd }}

linux:
  dotfiles: ~/.dotfiles
  link_type: 'Hard'
  shell_command: bash -c {{ quote "" cmd }}
