windows:
  dotfiles: ~/.dotfiles
  link_type: 'Symbolic'
  shell_command: powershell -noprofile -nologo -c {{ quote "" cmd }}
  variables:
    nf_latest_ver: v3.3.0

linux:
  dotfiles: ~/.dotfiles
  link_type: 'Hard'
  shell_command: bash -c {{ quote "" cmd }}
  variables:
    nf_latest_ver: v3.3.0
