#!/bin/bash

# USER_NAME=$USER
# su $USER_NAME -c 'main'
export ROTZ_INSTALL="/home/ameshram/.rotz"
export PATH="$ROTZ_INSTALL/bin:$PATH"

rotz install essentials/git
rotz install essentials/lazygit
rotz install essentials/bash
rotz install editor/*
rotz install extras/fonts
rotz install extras/apt

# Now link everything
rotz link essentials/git
rotz link essentials/lazygit
rotz link essentials/bash
rotz link editor/*
rotz link extras/starship
